server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: base-message
            preLogger: true
            postLogger: true
      routes:
        - id: user
          uri: http://localhost:8081/
          predicates:
            - Path=/user/**
        - id: product
          uri: http://localhost:8082/
          predicates:
            - Path=/product/**
          filters:
            - TokenFilter